spring.application.name=cms

# Database Connection (PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# strict validation prevents hibernate from creating tables automatically in production
# we will use Flyway for that, so we turn this off or set to validate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
# Uncomment below if you have a password
# spring.data.redis.password=${REDIS_PASSWORD}